NewsPortal/Controllers/BillingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using News.Model;
using News.Business;

namespace NewsPortal.Controllers
{
    public class BillingController : Controller
    {
        BillingBusiness objBusiness = new BillingBusiness();
        string CurrentUrl = "http://deshaurduniya.sagoni.com/";
        // GET: Billing
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult RenewalInvoice()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Index", "Admin");
            }
            List<BillingModel> InvoiceList = new List<BillingModel>();
            InvoiceList = objBusiness.GetInvoiceList("UpperMenu");
            return View(InvoiceList);
        }
        [HttpPost]
        public ActionResult UploadInvoice(BillingModel objModel, HttpPostedFileBase file)
        {
            try
            {
                if (file != null)
                {
                    //upload newsimage
                    string fileName = System.IO.Path.GetFileName(file.FileName);
                    objModel.InvoiceAttachment = "~/Invoice/" + fileName;
                    file.SaveAs(Server.MapPath(objModel.InvoiceAttachment));
                    objModel.InvoiceAttachment = CurrentUrl + "Invoice/" + fileName;
                }
            
                string result = objBusiness.SaveInvoice(objModel);
                if (result != null)
                {
                    return RedirectToAction("RenewalInvoice");
                }
                else
                {
                    ViewBag.message = "Something went Wrong.";
                    return View();
                }

            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

NewsPortal/Views/Billing/RenewalInvoice.cshtml
@model IEnumerable<News.Model.BillingModel>
@{

    ViewBag.Title = "UserLogin";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User List
    </h1>
    <ol class="breadcrumb">
   
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Renewal Date</th>
                                <th>Attachment</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                <td>@Html.DisplayFor(modelItem => item.BillingDate)</td>
                                <td>@Html.DisplayFor(modelItem => item.InvoiceAttachment)</td>
                                <td>
                                    <a href="@item.InvoiceAttachment" download>Download</a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

NewsPortal/Views/Billing/UploadInvoice.cshtml
@model News.Model.BillingModel
@{
                /**/

                Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/UpperMenu")" class="btn btn-default btn-success pull-right" style="color:white">Upper menu list</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Upper Menu Details</h3>
        </div>
        @using (Html.BeginForm("UploadInvoice", "Billing", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">

                        <div class="form-group col-md-4">
                            <label>Name</label>
                            <input type="text" name="MenuId" class="form-control" style="display:none" value="@Model.Id" />
                            <input type="date" name="MenuName" class="form-control" value="@Model.BillingDate" placeholder="Enter UserName" autocomplete="off" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Attachment</label>
                            <input type="hidden" name="InvoiceAttachment" value="@Model.InvoiceAttachment" autocomplete="off" />
                            <input type="file" name="file" id="file" class="form-control" value="@Model.InvoiceAttachment" autocomplete="off" />
                        </div>
                       
                    </div>

                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right" id="submit">Submit</button>
            </div>
            <!-- /.box-footer -->
        }
    </div>
    <!-- /.box -->
</section>