NewsPortal/Controllers/DropdownController.cs
using News.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using News.Model;

namespace NewsPortal.Controllers
{
    public class DropdownController : Controller
    {
       
        DropdownBusiness objBusiness = new DropdownBusiness();
        // GET: Dropdown
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _UpperMenuList(int selected = 0)
        {
            ViewBag.selectedId = selected;
            return PartialView(objBusiness.GetMenuList("UpperMenu"));
        }
        public ActionResult _LowerMenuList(int selected = 0)
        {
            ViewBag.selectedId = selected;
            return PartialView(objBusiness.GetMenuList("LowerMenu"));
        }
        public ActionResult _AdvCategoryList(int selected = 0)
        {
            ViewBag.selectedId = selected;
            return PartialView(objBusiness.GetAdvCategoryList());
        }
    }
}

NewsPortal/Views/Admin/Advertisement.cshtml
@model IEnumerable<News.Model.AdvertisementModel>
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        Advertisement List
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/CreateAdvertisement")" class="btn btn-default btn-success pull-right" style="color:white">Add Data</a></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>@Html.DisplayFor(modelItem => item.AdvertisementImage)</td>
                                    <td>@Html.DisplayFor(modelItem => item.AdvCategory)</td>
                                    <td>
                                        @Html.ActionLink("Delete", "DeleteAdvertisement", new { Id = item.Id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

NewsPortal/Views/Admin/Article.cshtml
@model IEnumerable<News.Model.ArticleModel>
@{

    ViewBag.Title = "UserLogin";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User List
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/CreateArticle")" class="btn btn-default btn-success pull-right" style="color:white">Add Article</a></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Headline</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Headline)</td>
                                    <td>
                                        @Html.ActionLink("Edit", "CreateArticle", new { Id = item.Id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

NewsPortal/Views/Admin/CreateLowerMenu.cshtml
@model News.Model.MenuModel
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/LowerMenu")" class="btn btn-default btn-success pull-right" style="color:white">Lower menu list</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Upper Menu Details</h3>
        </div>
        @using (Html.BeginForm("CreateLowerMenu", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">

                        <div class="form-group col-md-4">
                            <label>Name</label>
                            <input type="text" name="MenuId" class="form-control" style="display:none" value="@Model.MenuId" />
                            <input type="text" name="MenuName" class="form-control" value="@Model.MenuName" placeholder="Enter UserName" autocomplete="off" />
                        </div>
                    </div>

                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right" id="submit">Submit</button>
            </div>
            <!-- /.box-footer -->
        }
    </div>
    <!-- /.box -->
</section>

NewsPortal/Views/Admin/CreateLowerMenuNews.cshtml
@model News.Model.LowerMenuNewsModel
@{

    ViewBag.Title = "UserLogin";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<section class="content-header">
    <h1>
        Upper Menu Data
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/LowerMenuNews")" class="btn btn-default btn-success pull-right" style="color:white">Back To List</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Add Upper Menu Data</h3>
        </div>
        @using (Html.BeginForm("CreateLowerMenuNews", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="box-body">
                <div class="row">

                    <div class="col-md-12">

                        <input type="text" name="MenuId" class="form-control" style="display:none" value="@Model.Id" />
                        <div class="form-group ">
                            <label>Name</label>

                            @Html.Action("_LowerMenuList", "Dropdown", new { selected = @Model.MenuId })

                        </div>
                        <div class="form-group">
                            <label>Headline</label>
                            <input type="text" name="Headline" class="form-control" value="@Model.Headline" placeholder="Enter Headline" autocomplete="off" />
                        </div>
                        <div class="form-group">
                            <label>Image with size of H-117px and W-191px</label>
                            <input type="file" name="file" id="file" class="form-control" value="@Model.NewsImage" autocomplete="off" />
                        </div>
                        <div class="form-group">
                            <label>News</label>
                            <textarea id="editor1" name="NewsContent" rows="10" cols="80">@Model.NewsContent</textarea>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Image with size of H-117px and W-191px</label>
                            <input type="file" name="file2" id="file2" class="form-control" value="@Model.image2" autocomplete="off" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Video Link</label>
                            <input type="text" name="VideoLink" class="form-control" value="@Model.VideoLink" />
                        </div>
                        <div class="form-group">
                            <label>News</label>
                            <textarea id="editor2" name="NewsContent2" rows="10" cols="80">@Model.NewsContent2</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right" id="submit">Submit</button>
            </div>
            <!-- /.box-footer -->
        }
    </div>
    <!-- /.box -->
</section>

NewsPortal/Views/Admin/CreateTopHeadlineNews.cshtml
@model News.Model.TopHeadlineNewsModel
@{
                /**/


                ViewBag.Title = "UserLogin";
                Layout = "~/Views/Shared/_Layout2.cshtml";
}

<section class="content-header">
    <h1>
        Top Headline Data
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/LowerMenuNews")" class="btn btn-default btn-success pull-right" style="color:white">Back To List</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Add Top Headline Data</h3>
        </div>
        @using (Html.BeginForm("CreateTopHeadlineNews", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="box-body">
                <div class="row">

                    <div class="col-md-12">
                        <input type="text" name="MenuId" class="form-control" style="display:none" value="@Model.Id" />
                        <div class="form-group">
                            <label>Headline</label>
                            <input type="text" name="Headline" class="form-control" value="@Model.Headline" placeholder="Enter Headline" autocomplete="off" />
                        </div>
                        <div class="form-group">
                            <label>Image with size of H-117px and W-191px</label>
                            <input type="hidden" name="NewsImage" value="@Model.NewsImage" autocomplete="off" />
                            <input type="file" name="file" id="file" class="form-control"  autocomplete="off" />
                        </div>
                        <div class="form-group">
                            <label>News</label>
                            <textarea id="editor1" name="NewsContent" rows="10" cols="80">@Model.NewsContent</textarea>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Image with size of H-117px and W-191px</label>
                            <input type="hidden" name="image2" value="@Model.image2" autocomplete="off" />
                            <input type="file" name="file2" id="file2" class="form-control" autocomplete="off" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Video Link</label>
                            <input type="text" name="VideoLink" class="form-control" value="@Model.VideoLink" />
                        </div>
                        <div class="form-group">
                            <label>News</label>
                            <textarea id="editor2" name="NewsContent2" rows="10" cols="80">@Model.NewsContent2</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right" id="submit">Submit</button>
            </div>
            <!-- /.box-footer -->
        }
    </div>
    <!-- /.box -->
</section>

NewsPortal/Views/Admin/CreateUpperMenuNews.cshtml
@model News.Model.UpperMenuNewsModel
@{

    ViewBag.Title = "UserLogin";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<section class="content-header">
    <h1>
        Upper Menu Data
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/UpperMenuNews")" class="btn btn-default btn-success pull-right" style="color:white">Back To List</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Add Upper Menu Data</h3>
        </div>
        @using (Html.BeginForm("CreateUpperMenuNews", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="box-body">
                <div class="row">

                    <div class="col-md-12">

                        <input type="text" name="Id" class="form-control" style="display:none" value="@Model.Id" />
                        <div class="form-group ">
                            <label>Name</label>

                            @Html.Action("_UpperMenuList", "Dropdown", new { selected = @Model.MenuId })

                        </div>
                        <div class="form-group">
                            <label>Headline</label>
                            <input type="text" name="Headline" class="form-control" value="@Model.Headline" placeholder="Enter Headline" autocomplete="off" />
                        </div>
                        <div class="form-group">
                            <label>Image with size of H-117px and W-191px</label>
                            <input type="hidden" name="NewsImage" value="@Model.NewsImage" autocomplete="off" />
                            <input type="file" name="file" id="file" class="form-control" value="@Model.NewsImage" autocomplete="off" />
                        </div>
                        <div class="form-group">
                            <label>News</label>
                            <textarea id="editor1" name="NewsContent" rows="10" cols="80">@Model.NewsContent</textarea>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Image with size of H-117px and W-191px</label>
                            <input type="hidden" name="image2" value="@Model.image2" autocomplete="off" />
                            <input type="file" name="file2" id="file2" class="form-control" value="@Model.image2" autocomplete="off" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Video Link</label>
                            <input type="text" name="VideoLink" class="form-control" value="@Model.VideoLink" />
                        </div>
                        <div class="form-group">
                            <label>News</label>
                            <textarea id="editor2" name="NewsContent2" rows="10" cols="80">@Model.NewsContent2</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right" id="submit">Submit</button>
            </div>
            <!-- /.box-footer -->
        }
    </div>
    <!-- /.box -->
</section>

NewsPortal/Views/Admin/CreateVideo.cshtml
@model News.Model.VideoModel
@{

    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<section class="content-header">
    <h1>
        Advertisement
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/Video")" class="btn btn-default btn-success pull-right" style="color:white">Back To List</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Add Advertisement</h3>
        </div>
        @using (Html.BeginForm("CreateVideo", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="box-body">
                <div class="row">

                    <div class="col-md-12">
                        <input type="text" name="Id" class="form-control" style="display:none" value="@Model.Id" />
                        <div class="form-group">
                            <label>Heading</label>
                            <input type="text" name="Heading" class="form-control"  value="@Model.Heading" />
                        </div>
                        <div class="form-group">
                            <label>Video Link</label>
                            <input type="text" name="youtube_link" class="form-control" value="@Model.youtube_link" />
                        </div>
                        @*<div class="form-group">
                            <label>Content</label>
                            <textarea id="editor1" name="Content" rows="10" cols="80">
                                           @Model.Content
                    </textarea>
                        </div>*@
                       
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right" id="submit">Submit</button>
            </div>
            <!-- /.box-footer -->
        }
    </div>
    <!-- /.box -->
</section>

NewsPortal/Views/Admin/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Dashboard</h2>

<img src="~/Images/welcome.jpg" />

NewsPortal/Views/Admin/Index.cshtml
@model News.Model.UserModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Desh our duniya</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Scripts/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Scripts/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Scripts/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Scripts/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Scripts/plugins/iCheck/square/blue.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="~/Scripts/index2.html"><b>Welcome <br />Desh Our Duniya</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            @*<p class="login-box-msg">Sign in to start your session</p>*@
            @using (Html.BeginForm("index", "Admin", FormMethod.Post))
            {
                <div class="form-group has-feedback">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })

                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control", @type = "Password", @placeholder = "Password" } })
                    @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <a href="http://deshaurduniya.sagoni.com/">Back to Portal</a><br>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            }
            
            @*<a href="register.html" class="text-center">Register a new membership</a>*@
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery 3 -->
    <script src="~/Scripts/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Scripts/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="~/Scripts/plugins/iCheck/icheck.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
            });
        });
    </script>
</body>
</html>

NewsPortal/Views/Admin/LowerMenuNews.cshtml
@model IEnumerable<News.Model.LowerMenuNewsModel>
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User List
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/CreateLowerMenuNews")" class="btn btn-default btn-success pull-right" style="color:white">Add Data</a></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Menu Name</th>
                                <th>Headline</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.NewsImage)</td>
                                    <td>@Html.DisplayFor(modelItem => item.MenuName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Headline)</td>
                                    <td>
                                        @Html.ActionLink("Edit", "CreateLowerMenuNews", new { Id = item.MenuId })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

NewsPortal/Views/Admin/TopHeadlineNews.cshtml
@model IEnumerable<News.Model.TopHeadlineNewsModel>
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User List
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/CreateTopHeadlineNews")" class="btn btn-default btn-success pull-right" style="color:white">Add Data</a></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Headline</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Headline)</td>
                                    <td>
                                        @Html.ActionLink("Edit", "CreateTopHeadlineNews", new { Id = item.Id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

NewsPortal/Views/Admin/UpperMenu.cshtml
@model IEnumerable<News.Model.MenuModel>
@{

    ViewBag.Title = "UserLogin";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User List
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/CreateUpperMenu")" class="btn btn-default btn-success pull-right" style="color:white">Add Upper Menu</a></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.MenuId)</td>
                                    <td>@Html.DisplayFor(modelItem => item.MenuName)</td>
                                    <td>
                                        @Html.ActionLink("Edit", "CreateUpperMenu", new { Id = item.MenuId })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

NewsPortal/Views/Admin/UserLogin.cshtml
@model IEnumerable<News.Model.UserModel>
@{
    /**/

    ViewBag.Title = "UserLogin";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User List
    </h1>
    <ol class="breadcrumb">
        <li>
        <li><a href="@Url.Content("~/Admin/_createUserLogin")" class="btn btn-default btn-success pull-right" style="color:white">Add User</a></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>User Id</th>
                                <th>Name</th>
                                <th>Password</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.UserId)</td>
                                <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                                <td>@Html.DisplayFor(modelItem => item.UserPassword)</td>
                                <td>
                                    @Html.ActionLink("Edit", "_createUserLogin", new { Id = item.UserId })
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

NewsPortal/Views/Admin/_createUserLogin.cshtml
@model News.Model.UserModel
@{
    /**/

    ViewBag.Title = "_createUserLogin";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<section class="content-header">
    <h1>
        User
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/Admin/UserLogin")" class="btn btn-default btn-success pull-right" style="color:white">User List</a></li>
    </ol>
</section>
<section class="content">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Users Details</h3>
        </div>
        @using (Html.BeginForm("_createUserLogin", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                       
                        <div class="form-group col-md-4">
                            <label>Name</label>
                            <input type="text" name="UserId" class="form-control" style="display:none" value="@Model.UserId" />
                            <input type="text" name="UserName" class="form-control" value="@Model.UserName" placeholder="Enter UserName" autocomplete="off" />
                        </div>
                        <div class="form-group col-md-4">
                            <label>Password</label>
                            <input type="text" name="UserPassword" class="form-control" value="@Model.UserPassword" placeholder="Enter Password" />
                        </div>
                    </div>

                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right" id="submit">Submit</button>
            </div>
            <!-- /.box-footer -->
        }
    </div>
    <!-- /.box -->
</section>